name: contacts_rapide
description: Application CRUD de contacts avec Firebase

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Versions compatibles
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1

  # UI
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path: "assets/images/logo1.png"
  android: "launcher_icon"
  ios: true
  background_color: "#FFFFFF"
  android_min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/